version: 2
jobs:
  build:
    working_directory: ~/capstone_backend
    docker:
      - image: circleci/node:7.10
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: clam_backend_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres
          NODE_ENV: test
    steps:
      - checkout
      # Download and cache dependencies
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      # Wait for Postgres connection to open.
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Run validation checks & generate coverage reports
      - run: npm run mocha
